version: '3'

services:
  php:
    image: php:8.1.18-fpm
    volumes:
      - './src:/var/www/html'
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/curl/cacert.pem:/etc/cacert.pem
    # command: bash -c "chown -R www-data:www-data /var/www/html/downloads"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - php


