version: '3'

services:
  php:
    image: php:8.1.18-fpm
    volumes:
      - './src:/var/www/html'
    # command: bash -c "chown -R www-data:www-data /var/www/html/downloads"
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'


